INSERT INTO topics (slug,name_vi,name_en,icon,color,sort_order) VALUES
('finance','T?i ch?nh','Finance','??','#10b981',1),('hr','Nh?n s?','Human Resources','??','#6366f1',2),('marketing','Marketing','Marketing','??','#f59e0b',3),('travel','Du l?ch & Giao th?ng','Travel','??','#06b6d4',4),('food','?n u?ng & Nh? h?ng','Food','???','#ef4444',5),('health','Y t? & S?c kh?e','Health','??','#14b8a6',6),('office','V?n ph?ng & Thi?t b?','Office','??','#8b5cf6',7),('retail','Mua s?m & B?n l?','Retail','??','#f97316',8),('manufacturing','S?n xu?t & K? thu?t','Manufacturing','??','#64748b',9),('real-estate','B?t ??ng s?n','Real Estate','???','#84cc16',10),('technology','C?ng ngh? & IT','Technology','??','#3b82f6',11),('environment','M?i tr??ng & N?ng l??ng','Environment','??','#22c55e',12);
INSERT INTO words (word,phonetic,word_type,meaning_vi,meaning_en,example_sentence,example_vi,synonyms,confusables,collocations,level,topic_id,toeic_parts) VALUES
('budget','/?b?d??t/','noun','ng?n s?ch','planned spending','The budget was approved.','Ng?n s?ch ?? ???c duy?t.',ARRAY['fund'],ARRAY['badge'],ARRAY['annual budget'],'foundation',1,ARRAY[5,6,7]),
('invoice','/??nv??s/','noun','h?a ??n','bill','Please send the invoice today.','Vui l?ng g?i h?a ??n h?m nay.',ARRAY['bill'],ARRAY['invite'],ARRAY['issue an invoice'],'foundation',1,ARRAY[5,6]),
('recruit','/r??kru?t/','verb','tuy?n d?ng','hire','We need to recruit staff.','Ch?ng ta c?n tuy?n nh?n vi?n.',ARRAY['hire'],ARRAY['require'],ARRAY['recruit candidates'],'foundation',2,ARRAY[2,5,6]),
('campaign','/k?m?pe?n/','noun','chi?n d?ch','promotion','The campaign increased sales.','Chi?n d?ch t?ng doanh s?.',ARRAY['promotion'],ARRAY['company'],ARRAY['launch a campaign'],'intermediate',3,ARRAY[4,5,7]),
('itinerary','/a??t?n?reri/','noun','l?ch tr?nh','travel plan','Review the itinerary.','Xem l?i l?ch tr?nh.',ARRAY['schedule'],ARRAY['stationery'],ARRAY['travel itinerary'],'intermediate',4,ARRAY[3,4,7]);
INSERT INTO achievements (slug,name_vi,description,icon,xp_reward,condition_type,condition_value) VALUES
('first-word','Kh?i ??u','H?c t? ??u ti?n','??',10,'words_learned',1),('streak-7','Streak 7 ng?y','H?c 7 ng?y li?n ti?p','??',150,'streak',7),('words-100','H?c 100 t?','Ghi nh? 100 t?','??',200,'words_learned',100),('quiz-perfect','Quiz ho?n h?o','??ng 10/10','??',100,'quiz_score',10),('combo-5','Combo x5','??ng 5 c?u li?n ti?p','?',80,'combo',5);
